language: php
php:
  - '7.1'
  - hhvm # on Trusty only
  - nightly

before_script:
    - pecl install redis
    - composer install
#    - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

script:
    - phpunit tests

services:
    - redis
